<a href="https://colab.research.google.com/github/Jaskirat1/AIT_numpy/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intro to Numpy arrays 


In [2]:
#**How to append an array in another array**

import numpy as np
arr1 = np.array([[1,2,3],[2,3,4]])
arr2 = np.array([[4,5,6]])

arr1= np.append(arr1,arr2, 0)
print(arr1)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


Difference between ndmin and ndim

In [3]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)



[[[[[1 2 3 4]]]]]
5


Creating dimensional arrays

In [4]:
import numpy as np
arr = np.array(5)   # 0-D array
print(arr)
print(arr.ndim)

5
0


In [5]:
arr2 = np.array([1,2,4,45,6])
print(arr2)       # 1-D array
print(arr2.ndim)


[ 1  2  4 45  6]
1


In [6]:
arr3 = np.array([[1,2,3],[2,3,4]])
print(arr3)       # 2-D array
print(arr3.ndim)

[[1 2 3]
 [2 3 4]]
2


In [7]:
arr4 = np.array([
    [
    [1,2,3,4],
    [5,6,7,8]
     ],
    [
    [1,2,4,5],
    [5,7,7,8]
    ]
])
print(arr4)
print(arr4.ndim)      # 3 -D array

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 4 5]
  [5 7 7 8]]]
3


In [8]:
arr5 = np.array([[
[
    [1,2,3],
    [4,5,6]
],
[
    [4,6,7],
    [6,7,8]
],
[
    [6,7,8],
    [9,2,4]
],

]
])
print(arr5)
print(arr5.ndim)        # 4-D array

[[[[1 2 3]
   [4 5 6]]

  [[4 6 7]
   [6 7 8]]

  [[6 7 8]
   [9 2 4]]]]
4


In [9]:
#Higher Dimensional array

arr6=  np.array([1,2,3,4,5], ndmin = 5)
arr6

array([[[[[1, 2, 3, 4, 5]]]]])

In [10]:
type(arr6)

numpy.ndarray

In [11]:
arr6.ndim

5